name: Checkout
on: [push]
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        with:
          ref: bleeding
      - run: chmod u+x ./gradlew
      - run: ./gradlew clean build
      - run: chmod u+x ./start.sh
      - run: ./start.sh ${{ secrets.SSH_PWD }}